# Generated by Django 4.0.4 on 2022-04-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=' ', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=256)),
                ('back', models.CharField(max_length=256)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.set')),
            ],
        ),
    ]
